name: Traffic_Locale
description: A Project made by Pavan Sastry NVSS..Mainly made for Personal Use.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_slidable: ^2.0.0
  intl: ^0.17.0
  flutter_osm_plugin: ^0.39.1
  latlong: ^0.6.1
  flutter_map: any
  flutter_map_marker_cluster: any
  sqflite: ^1.3.0
  share: ^2.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/ProfilePic.jpg


  
  uses-material-design: true
  